version: &imageVersion "11473734968"
global:
  version: *imageVersion
okto-sdk-react-template-app:
  environment: production
  project: okto
  namespaceOverride: oktohq
  image:
    registry: ghcr.io
    repository: okto-hq/okto-sdk-react-template-app
    pullPolicy: IfNotPresent
    tag: *imageVersion
  imagePullSecrets:
    - name: oktohq-registry
  deployment:
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 300Mi
    readinessProbe:
      failureThreshold: 10
      httpGet:
        path: /
        port: 3000
        scheme: HTTP
      initialDelaySeconds: 3
      periodSeconds: 2
    DDService: okto-sdk-react-template-app
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: node
        whenUnsatisfiable: ScheduleAnyway
  service:
    # serviceName: 
    ports:
      - port: 3000
        portName: http
        protocol: TCP
    type: ClusterIP
  ingress:
    enabled: true
    domain: okto.tech
    exposePort: http
    scheme: http
    hosts:
      - host: react-template.okto.tech
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
  env:
    WDS_SOCKET_PORT: "443"
  envFromSecrets:
    - variable: REACT_APP_OKTO_CLIENT_API_KEY
      secretId: &oktohq-sdk-docs oktohq/okto-sdk-react-template-app
      secretKey: REACT_APP_OKTO_CLIENT_API_KEY
    - variable: REACT_APP_GOOGLE_CLIENT_ID
      secretId: *oktohq-sdk-docs
      secretKey: REACT_APP_GOOGLE_CLIENT_ID
  tolerations:
    - effect: NoSchedule
      key: application
      operator: Equal
      value: okto
    - effect: NoSchedule
      key: arch
      operator: Equal
      value: arm64
  nodeSelector:
    application: okto
    arch: arm64
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
    runAsGroup: 7777
    runAsUser: 7777
  deploymentStrategy:
    rollingUpdate:
      maxUnavailable: 50%
