# syntax=docker.io/docker/dockerfile:1.7-labs
## Above is added for using exclude in COPY statement.
FROM node:20-alpine3.17 AS build

# OS Packages
RUN apk add --update --no-cache dumb-init

WORKDIR /app
COPY package.json ./

RUN npm install

COPY . .


RUN npm run build
RUN npm install
## Above is needed as npm run build is doing some changes and build fails with typescript version error

FROM node:20-alpine3.17 AS app

LABEL MAINTAINER Nishith Kulshrestha <nishith.kulshrestha@coindcx.com>

COPY --from=build /usr/bin/dumb-init /usr/bin/dumb-init

# Non-Root user
RUN addgroup -g 7777 dcx &&\
    adduser -D -h /home/dcx dcx -s /bin/false -u 7777 -G dcx

USER dcx
RUN mkdir /home/dcx/app
WORKDIR /home/dcx/app

# setup project structure
COPY --chown=dcx:dcx --from=build /app/build ./build

COPY  --chown=dcx:dcx  . .
COPY --chown=dcx:dcx --from=build /app/package-lock.json ./package-lock.json
RUN ls -la

# only install production dependencies
RUN npm ci --only=production

ENTRYPOINT [ "/usr/bin/dumb-init", "--" ]
CMD [ "./deployment/entrypoint.sh" ]
